import os
from typing import Tuple

# Suppress TensorFlow warnings/errors
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'

from bert_score import BERTScorer


def evaluate(generations: list[str], grounds: list[str], device='cpu', batch_size=32) -> Tuple[float, float, float]:
    """
    Takes the list of generated text and list of expected ground truth
    and returns precision, recall and F1 score

    :param generations: list of output generated by the model
    :param grounds: gpt 5.1 returned output (ideal summary)
    :param device: device in which evaluation should run
    :param batch_size: same arg passed to Bert Score
    :return: precision, recall and F1 score
    """
    scorer = BERTScorer(model_type='facebook/bart-large', device=device, batch_size=batch_size)
    return scorer.score(generations, grounds)


if __name__ == '__main__':
    # for testing

    generation = "i have bought an owl, but now it wants to fly away"
    ground = "an owl was bought, and it wants to fly to the grocery store"

    P, R, F1 = evaluate([generation], [ground], device='cpu')
    print(f"Precision: {P[0]:.4f}")
    print(f"Recall: {R[0]:.4f}")
    print(f"F1: {F1[0]:.4f}")
